---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "go"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "go"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "github_actions"
  - package-ecosystem: "npm"
    directory: "/api-tests"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "javascript"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "javascript"
  - package-ecosystem: "npm"
    directory: "/cli-tests"
    schedule:
      interval: "weekly"
    labels:
      - "auto-update-base"
      - "dependencies"
      - "javascript"
