apiVersion: v1
kind: Namespace
metadata:
  name: db-client
  labels:
    name: db-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: db-client
  labels:
    name: mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-client
  template:
    metadata:
      labels:
        name: mysql-client
    spec:
      containers:
        - name: mysql-client
          image: percona/percona-server:8.0
          imagePullPolicy: Always
          command:
          - sleep
          - infinity
