apiVersion: v1
kind: Namespace
metadata:
  name: db-client
  labels:
    name: db-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psmdb-client
  namespace: db-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: psmdb-client
  template:
    metadata:
      labels:
        name: psmdb-client
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: psmdb-client
          image: percona/percona-server-mongodb:7.0
          imagePullPolicy: Always
          command:
          - sleep
          - infinity
