---
name: CLI tests
on:
  workflow_call:
    inputs:
      make_target:
        description: 'Make target to execute'
        type: string
        required: true

jobs:
  integration_tests:
    strategy:
      fail-fast: true
    continue-on-error: false
    name: CLI ${{inputs.make_target}}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PERCONA_VERSION_SERVICE_URL: https://check-dev.percona.com/versions/v1
      MAKE_TARGET: ${{ inputs.make_target }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go release
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
      # https://minikube.sigs.k8s.io/docs/drivers/docker/
      - name: Configure minikube
        working-directory: cli-tests
        run: |
          minikube delete --all --purge
          rm -rf ~/.minikube
          minikube config set cpus 2
          minikube start

      - name: Build CLI binary
        run: |
          make build-cli

      - name: Init ${{ env.MAKE_TARGET }} integration tests
        working-directory: cli-tests
        run: |
          make init

      - name: Run ${{ env.MAKE_TARGET }} integration tests
        working-directory: cli-tests
        id: cli-tests
        run: |
          make ${{ env.MAKE_TARGET }}

      - name: Collect logs from backend
        if: ${{ always() && steps.cli-tests.outcome != 'success' }}
        working-directory: cli-tests
        run: 'echo "here should be a command to extract and save backend logs"'

      - name: Attach the report
        if: ${{ always() && steps.cli-tests.outcome != 'skipped' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MAKE_TARGET }}-report
          path: cli-tests/test-report
          overwrite: true
